In [1]:
print("Hello")


Hello


In [2]:
import numpy as np


In [3]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [4]:
a.ndim


2

In [5]:
a.dtype

dtype('int32')

In [6]:
a.size

6

In [9]:
arr=np.array([2,6,7,4,19,45])
np.sort(arr)


array([ 2,  4,  6,  7, 19, 45])

In [10]:
np.arange(2,15,4)

array([ 2,  6, 10, 14])

In [12]:
arr[2:]


array([ 7,  4, 19, 45])

In [13]:
b = np.arange(1, 10)

matrix = b.reshape(3, 3)

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
